apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: elliot-rs
spec:
  replicas: 4
  selector:
    matchExpressions:
    - key: app
      operator: In
      values: 
      - profile
  template:
    metadata:
      name: azureus
      labels:
        app: profile
    spec:
      containers:
      - name: azureus
        image: ndevopsinsiders/profile:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80



